version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    ports:
      - 5000:4000
    environment:
      PORT: 4000
      mongo_url: mongodb://mongo_db:27017/todo
    depends_on:
      - mongo_db
  
volumes:
  mongodb_data: